"""empty message

Revision ID: 508a0e5256ed
Revises: 443458515d26
Create Date: 2023-04-24 23:21:43.410424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '508a0e5256ed'
down_revision = '443458515d26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rw_records', sa.Column('winner', sa.Integer(), nullable=False))
    op.drop_column('rw_records', 'is_ended')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rw_records', sa.Column('is_ended', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('rw_records', 'winner')
    # ### end Alembic commands ###
