"""empty message

Revision ID: 443458515d26
Revises: f191a88acaa8
Create Date: 2023-04-24 17:48:46.391982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443458515d26'
down_revision = 'f191a88acaa8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
