"""empty message

Revision ID: f25ed35803f0
Revises: 508a0e5256ed
Create Date: 2023-04-25 12:52:20.505196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25ed35803f0'
down_revision = '508a0e5256ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
