"""empty message

Revision ID: dbebd6f20a65
Revises: f25ed35803f0
Create Date: 2023-04-25 12:56:46.759667

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dbebd6f20a65'
down_revision = 'f25ed35803f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rw_records', 'id', type_=sa.Integer, primary_key=True, nullable=False, autoincrement=False)
    op.alter_column('rw_records', 'start_time', type_=sa.BigInteger, nullable=False)
    op.alter_column('rw_records', 'end_time', type_=sa.BigInteger)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rw_records', 'id', type_=sa.Integer, primary_key=True, nullable=False, autoincrement=True)
    op.alter_column('rw_records', 'start_time', type_=sa.DateTime, nullable=False)
    op.alter_column('rw_records', 'end_time', type_=sa.DateTime)
    # ### end Alembic commands ###
