"""empty message

Revision ID: 27bd63bf9dca
Revises: 650a05b27047
Create Date: 2023-04-24 02:24:56.126227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27bd63bf9dca'
down_revision = '650a05b27047'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
