"""Add email column to users table

Revision ID: d36c1c4006b2
Revises: ab86865c4202
Create Date: 2023-04-24 01:52:50.157529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36c1c4006b2'
down_revision = 'ab86865c4202'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
